#!/usr/bin/env python3
"""
Genesis v0.3 - The Creation Script
Summons Python Accurate Angel into existence.

Run: python genesis.py
"""

import os
from pathlib import Path

# ============================================================================
# CONFIGURATION
# ============================================================================

PROJECT_NAME = "PythonAccurateAngel"
BASE_DIR = Path(".")

# ============================================================================
# FILE CONTENTS
# ============================================================================

FILES = {
    "requirements.txt": """watchdog==4.0.0
rich==13.7.0
networkx==3.2.1
pyvis==0.3.2
pyyaml==6.0.1
pydantic>=2.0.0
anthropic>=0.18.0
""",

    "angel_config.yaml": """angel_settings:
  name: "Ophanim-01"
  version: "2.0.0"

theme:
  primary: "#FF69B4"
  secondary: "#FFD700"
  background: "#000000"
  alert: "#FF1493"
  text: "#FFFFFF"

vision:
  watch_path: "./"
  debounce_seconds: 2.0
  ignore_patterns:
    - "*.git*"
    - "*__pycache__*"
    - "*.env"
    - "*.DS_Store"
    - "*.html"
    - "*.tmp*"
    - "*~"
    - "*.jsonl"

brain:
  provider: "mock"
  auto_confirm: false

halo:
  max_daily_cost_usd: 1.00
  emergency_stop_file: "STOP_ANGEL"
""",

    "angel/__init__.py": """# Python Accurate Angel - Divine Modules
""",

    "angel/types.py": '''from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime
import uuid


class EdgeDef(BaseModel):
    """Defines a relationship between two nodes."""
    source: str
    target: str
    edge_type: Literal["implements", "modifies", "deprecates", "relates_to"] = "relates_to"


class Proposal(BaseModel):
    """A proposed relationship generated by the Brain."""
    proposal_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    work_unit_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    confidence: float = Field(ge=0.0, le=1.0)
    edge: EdgeDef
    rationale: str
    diff_summary: Optional[str] = None


class AngelEvent(BaseModel):
    """An immutable event in the Chronicles."""
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    action_type: Literal[
        "WORK_UNIT_CAPTURED", "PROPOSAL_GENERATED",
        "PROPOSAL_CONFIRMED", "PROPOSAL_REJECTED", "INTENT_CREATED"
    ]
    actor: Literal["Human", "AI_Agent"] = "AI_Agent"
    file_path: Optional[str] = None
    proposal_id: Optional[str] = None
    edge: Optional[EdgeDef] = None
    justification: Optional[str] = None
    explicit_approval: Optional[bool] = None
    intent_label: Optional[str] = None


class Intent(BaseModel):
    """A fuzzy human intent node."""
    intent_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    label: str
    description: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
''',

    "angel/chronicles.py": '''import json
from typing import List, Optional
from pathlib import Path
from .types import AngelEvent


class TheScribe:
    """Append-only JSONL event storage. The ground truth."""

    def __init__(self, chronicles_path: str = "angel_chronicles.jsonl"):
        self.chronicles_path = Path(chronicles_path)
        if not self.chronicles_path.exists():
            self.chronicles_path.touch()

    def record(self, event: AngelEvent) -> None:
        with open(self.chronicles_path, "a", encoding="utf-8") as f:
            f.write(event.model_dump_json() + "\\n")

    def read_all(self) -> List[AngelEvent]:
        events = []
        if not self.chronicles_path.exists():
            return events
        with open(self.chronicles_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        events.append(AngelEvent(**json.loads(line)))
                    except (json.JSONDecodeError, ValueError):
                        continue
        return events

    def get_last_event(self) -> Optional[AngelEvent]:
        events = self.read_all()
        return events[-1] if events else None

    def count(self) -> int:
        return len(self.read_all())
''',

    "angel/voice.py": '''from rich.console import Console
from rich.theme import Theme
from rich.panel import Panel
from rich.text import Text
from datetime import datetime

angel_theme = Theme({
    "angel.pink": "#FF69B4",
    "angel.gold": "#FFD700",
    "angel.alert": "bold red on #FFD700"
})

console = Console(theme=angel_theme)


class TheHerald:
    def __init__(self, name="Angel"):
        self.name = name

    def speak(self, message, style="angel.pink"):
        timestamp = datetime.now().strftime("%H:%M:%S")
        console.print(f"[{timestamp}] [bold]{self.name}:[/] {message}", style=style)

    def proclaim(self, title, content):
        text = Text(content, justify="center", style="black")
        panel = Panel(text, title=f"[bold #000000]{title}[/]",
                      border_style="angel.gold", style="on #FF69B4", padding=(1, 2))
        console.print(panel)

    def alert(self, message):
        console.print(f"[bold red]ALERT:[/] {message}", style="angel.gold")
''',

    "angel/eyes.py": '''from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from threading import Timer


class TheAllSeeingEye(FileSystemEventHandler):
    def __init__(self, callback, debounce_interval=2.0, ignore_patterns=None):
        self.callback = callback
        self.debounce_interval = debounce_interval
        self.ignore_patterns = ignore_patterns or []
        self.timer = None
        self.last_event_path = None

    def _is_ignored(self, path):
        for pattern in self.ignore_patterns:
            if pattern.replace("*", "") in path:
                return True
        return False

    def _process_event(self):
        if self.last_event_path:
            self.callback(self.last_event_path)

    def on_modified(self, event):
        if event.is_directory or self._is_ignored(event.src_path):
            return
        if self.timer:
            self.timer.cancel()
        self.last_event_path = event.src_path
        self.timer = Timer(self.debounce_interval, self._process_event)
        self.timer.start()


class VisionSystem:
    def __init__(self, path, callback, config):
        self.observer = Observer()
        self.handler = TheAllSeeingEye(
            callback, config["vision"]["debounce_seconds"],
            config["vision"]["ignore_patterns"]
        )
        self.path = path

    def open_eyes(self):
        self.observer.schedule(self.handler, self.path, recursive=True)
        self.observer.start()

    def close_eyes(self):
        self.observer.stop()
        self.observer.join()
''',

    "angel/wheels.py": '''import networkx as nx
from pyvis.network import Network
from typing import List
from .types import AngelEvent, EdgeDef


class Sephirot:
    """The Knowledge Graph. State derived from Chronicles."""

    def __init__(self):
        self.graph = nx.DiGraph()
        self.c_file = "#FFD700"
        self.c_intent = "#FF69B4"
        self.edge_colors = {
            "implements": "#00FF00", "modifies": "#FFA500",
            "deprecates": "#FF0000", "relates_to": "#FFFFFF"
        }

    def clear(self):
        self.graph.clear()

    def add_file_node(self, filename: str):
        if filename not in self.graph:
            self.graph.add_node(filename, label=filename, color=self.c_file,
                                shape="square", size=25, node_type="file")

    def add_intent_node(self, intent_label: str):
        if intent_label not in self.graph:
            self.graph.add_node(intent_label, label=intent_label, color=self.c_intent,
                                shape="dot", size=20, node_type="intent")

    def add_edge(self, edge: EdgeDef):
        self.add_file_node(edge.source)
        self.add_intent_node(edge.target)
        color = self.edge_colors.get(edge.edge_type, "#FFFFFF")
        self.graph.add_edge(edge.source, edge.target, color=color, title=edge.edge_type)

    def rebuild_from_chronicles(self, events: List[AngelEvent]):
        self.clear()
        for event in events:
            if event.action_type == "PROPOSAL_CONFIRMED" and event.edge:
                self.add_edge(event.edge)

    def get_stats(self) -> dict:
        nodes = list(self.graph.nodes(data=True))
        return {
            "total_nodes": len(nodes),
            "files": sum(1 for _, d in nodes if d.get("node_type") == "file"),
            "intents": sum(1 for _, d in nodes if d.get("node_type") == "intent"),
            "edges": self.graph.number_of_edges()
        }

    def manifest(self, output_file: str = "angel_traceability.html"):
        net = Network(height="750px", width="100%", bgcolor="#000000", font_color="white")
        net.from_nx(self.graph)
        net.force_atlas_2based(gravity=-50, central_gravity=0.01,
                               spring_length=100, spring_strength=0.08)
        net.save_graph(output_file)
        return output_file
''',

    "angel/halo.py": '''import os


class HaloSystem:
    def __init__(self, config):
        self.max_cost = config["halo"]["max_daily_cost_usd"]
        self.stop_file = config["halo"]["emergency_stop_file"]
        self.current_spend = 0.0

    def check_safety(self):
        if os.path.exists(self.stop_file):
            return False, "Emergency Stop File Detected!"
        if self.current_spend >= self.max_cost:
            return False, "Mana Pool Depleted"
        return True, "Systems Normal"

    def record_spend(self, cost):
        self.current_spend += cost
''',

    "angel/brain.py": '''import os
import subprocess
from typing import Optional
from .types import Proposal, EdgeDef
import uuid


class TheBrain:
    """Analyzes diffs and proposes relationships."""

    def __init__(self, config: dict):
        self.config = config
        self.provider = config.get("brain", {}).get("provider", "mock")
        self.api_key = os.environ.get("ANTHROPIC_API_KEY")

    def get_diff(self, file_path: str) -> Optional[str]:
        try:
            result = subprocess.run(["git", "diff", file_path],
                                    capture_output=True, text=True, cwd=".")
            return result.stdout if result.stdout.strip() else None
        except Exception:
            return None

    def analyze_intent(self, file_path: str) -> Proposal:
        diff = self.get_diff(file_path)
        work_unit_id = str(uuid.uuid4())[:8]
        filename = os.path.basename(file_path)
        intent = self._guess_intent(filename, diff)
        return Proposal(
            work_unit_id=work_unit_id, confidence=0.7,
            edge=EdgeDef(source=filename, target=intent, edge_type="implements"),
            rationale=f"Detected modification in {filename}. Related to: {intent}",
            diff_summary=self._summarize_diff(diff) if diff else "No diff"
        )

    def _guess_intent(self, filename: str, diff: Optional[str]) -> str:
        fn = filename.lower()
        if "test" in fn: return "Testing"
        if "config" in fn: return "Configuration"
        if "ui" in fn or "voice" in fn: return "User Interface"
        if diff and "fix" in diff.lower(): return "Bug Fix"
        return "General Development"

    def _summarize_diff(self, diff: str) -> str:
        lines = diff.split("\\n")
        adds = sum(1 for l in lines if l.startswith("+") and not l.startswith("+++"))
        dels = sum(1 for l in lines if l.startswith("-") and not l.startswith("---"))
        return f"+{adds}/-{dels} lines"
''',

    "main.py": '''import time
import yaml
import os
from rich.prompt import Prompt
from rich.table import Table

from angel.voice import TheHerald, console
from angel.eyes import VisionSystem
from angel.wheels import Sephirot
from angel.halo import HaloSystem
from angel.brain import TheBrain
from angel.chronicles import TheScribe
from angel.types import AngelEvent, EdgeDef

with open("angel_config.yaml", "r") as f:
    config = yaml.safe_load(f)

voice = TheHerald(name=config["angel_settings"]["name"])
halo = HaloSystem(config)
wheels = Sephirot()
brain = TheBrain(config)
scribe = TheScribe("angel_chronicles.jsonl")

existing = scribe.read_all()
if existing:
    wheels.rebuild_from_chronicles(existing)
    voice.speak(f"Restored {len(existing)} events.", style="angel.gold")


def display_proposal(p):
    t = Table(title="Proposed Relationship", border_style="bright_magenta")
    t.add_column("Field", style="cyan")
    t.add_column("Value", style="white")
    t.add_row("File", p.edge.source)
    t.add_row("Intent", p.edge.target)
    t.add_row("Type", p.edge.edge_type)
    t.add_row("Confidence", f"{p.confidence:.0%}")
    t.add_row("Rationale", p.rationale)
    console.print(t)


def handle_change(file_path):
    safe, msg = halo.check_safety()
    if not safe:
        voice.alert(f"HALO: {msg}")
        return

    filename = os.path.basename(file_path)
    voice.speak(f"Shift detected: [u]{filename}[/u]", style="angel.gold")
    scribe.record(AngelEvent(action_type="WORK_UNIT_CAPTURED", file_path=filename))

    proposal = brain.analyze_intent(file_path)
    scribe.record(AngelEvent(action_type="PROPOSAL_GENERATED",
                             file_path=filename, proposal_id=proposal.proposal_id))

    console.print()
    display_proposal(proposal)
    console.print()

    auto = config.get("brain", {}).get("auto_confirm", False)
    if auto:
        voice.speak("Auto-confirming.", style="angel.gold")
        choice = "y"
    else:
        choice = Prompt.ask("[magenta]Link?[/]", choices=["y", "n", "e"], default="y")

    if choice == "y":
        scribe.record(AngelEvent(action_type="PROPOSAL_CONFIRMED", actor="Human",
                                 file_path=filename, edge=proposal.edge, explicit_approval=True))
        wheels.add_edge(proposal.edge)
        voice.speak("Confirmed.", style="angel.pink")
    elif choice == "n":
        scribe.record(AngelEvent(action_type="PROPOSAL_REJECTED", actor="Human",
                                 file_path=filename, explicit_approval=False))
        voice.speak("Rejected.", style="angel.gold")
    elif choice == "e":
        custom = Prompt.ask("[cyan]Your intent?[/]")
        if custom.strip():
            edge = EdgeDef(source=filename, target=custom.strip(), edge_type="implements")
            scribe.record(AngelEvent(action_type="PROPOSAL_CONFIRMED", actor="Human",
                                     file_path=filename, edge=edge, explicit_approval=True))
            wheels.add_edge(edge)
            voice.speak(f"Custom: {filename} -> {custom}", style="angel.pink")

    wheels.manifest()
    s = wheels.get_stats()
    voice.speak(f"{s['files']} files, {s['intents']} intents, {s['edges']} links", style="angel.pink")


def main():
    auto = config.get("brain", {}).get("auto_confirm", False)
    mode = "AUTO-CONFIRM" if auto else "[Y/N/E]"
    voice.proclaim("BE NOT AFRAID",
                   f"Python Accurate Angel v{config['angel_settings']['version']}\\n"
                   f"Watching: {os.path.abspath(config['vision']['watch_path'])}\\n{mode}")

    eyes = VisionSystem(config["vision"]["watch_path"], handle_change, config)
    eyes.open_eyes()

    try:
        while True:
            time.sleep(1)
            safe, msg = halo.check_safety()
            if not safe:
                voice.alert(f"SHUTDOWN: {msg}")
                break
    except KeyboardInterrupt:
        voice.speak("Returning to the ether...", style="angel.pink")
    finally:
        eyes.close_eyes()


if __name__ == "__main__":
    main()
'''
}

# ============================================================================
# GENESIS RITUAL
# ============================================================================

def create_project():
    print("=" * 60)
    print("  GENESIS v0.3 - Summoning Python Accurate Angel")
    print("=" * 60)
    print()

    # Create angel/ directory
    angel_dir = BASE_DIR / "angel"
    angel_dir.mkdir(exist_ok=True)
    print(f"[+] Created directory: angel/")

    # Create all files
    for filepath, content in FILES.items():
        full_path = BASE_DIR / filepath
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        print(f"[+] Created: {filepath}")

    print()
    print("=" * 60)
    print("  GENESIS COMPLETE")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. pip install -r requirements.txt")
    print("  2. python main.py")
    print()
    print("The Angel awaits. Be not afraid.")


if __name__ == "__main__":
    create_project()
