from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime
import uuid


class EdgeDef(BaseModel):
    """Defines a relationship between two nodes."""
    source: str
    target: str
    edge_type: Literal["implements", "modifies", "deprecates", "relates_to"] = "relates_to"


class Proposal(BaseModel):
    """
    A proposed relationship generated by the Brain.
    Requires human confirmation before becoming truth.
    """
    proposal_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    work_unit_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    confidence: float = Field(ge=0.0, le=1.0)
    edge: EdgeDef
    rationale: str
    diff_summary: Optional[str] = None


class AngelEvent(BaseModel):
    """
    An immutable event in the Chronicles.
    The sequence of events IS the truth.
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    action_type: Literal[
        "WORK_UNIT_CAPTURED",
        "PROPOSAL_GENERATED",
        "PROPOSAL_CONFIRMED",
        "PROPOSAL_REJECTED",
        "INTENT_CREATED"
    ]
    actor: Literal["Human", "AI_Agent"] = "AI_Agent"

    # Contextual fields (optional based on action_type)
    file_path: Optional[str] = None
    proposal_id: Optional[str] = None
    edge: Optional[EdgeDef] = None
    justification: Optional[str] = None
    explicit_approval: Optional[bool] = None
    intent_label: Optional[str] = None


class Intent(BaseModel):
    """
    A fuzzy human intent node (e.g., "Make it flowy", "Fix jitter").
    First-class citizen in the knowledge graph.
    """
    intent_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    label: str
    description: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
